
services:
  php:
    container_name: php
    build: Docker/php
    expose:
      - "9000"
    volumes:
        - .:/var/www/html
    networks:
      - my_network

  nginx:
    container_name: nginx
    image: nginx:1.21.6
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/logs/error.log:/var/log/nginx/error.log:rw
      - ./Docker/nginx/logs/access.log:/var/log/nginx/access.log:rw
    depends_on:
      - php
    networks:
      - my_network
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
    networks:
      - my_network
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - my_network
###< symfony/mailer ###

networks:
  my_network:
    driver: bridge
